# Generated by Django 4.2.21 on 2025-08-24 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0008_course_themembers_product_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="TheMembersProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_id",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="ID do Produto TheMembers",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL da Imagem"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="active", max_length=20, verbose_name="Status"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última Sincronização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto TheMembers",
                "verbose_name_plural": "Produtos TheMembers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TheMembersSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("products", "Produtos"),
                            ("users", "Usuários"),
                            ("subscriptions", "Assinaturas"),
                            ("full", "Sincronização Completa"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Sincronização",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Sucesso"),
                            ("partial", "Parcial"),
                            ("failed", "Falhou"),
                        ],
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "items_processed",
                    models.IntegerField(default=0, verbose_name="Itens Processados"),
                ),
                (
                    "items_success",
                    models.IntegerField(default=0, verbose_name="Itens com Sucesso"),
                ),
                (
                    "items_failed",
                    models.IntegerField(default=0, verbose_name="Itens com Falha"),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Iniciado em"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Concluído em"
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Duração (segundos)"
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True, null=True, verbose_name="Detalhes da Sincronização"
                    ),
                ),
                (
                    "errors",
                    models.TextField(
                        blank=True, null=True, verbose_name="Erros Encontrados"
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Sincronização TheMembers",
                "verbose_name_plural": "Logs de Sincronização TheMembers",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="TheMembersWebhookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "webhook_type",
                    models.CharField(
                        choices=[
                            ("subscription_created", "Assinatura Criada"),
                            ("subscription_cancelled", "Assinatura Cancelada"),
                            ("payment_confirmed", "Pagamento Confirmado"),
                            ("user_created", "Usuário Criado"),
                            ("other", "Outro"),
                        ],
                        max_length=50,
                        verbose_name="Tipo do Webhook",
                    ),
                ),
                ("payload", models.JSONField(verbose_name="Payload do Webhook")),
                (
                    "headers",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Headers do Webhook"
                    ),
                ),
                (
                    "processed",
                    models.BooleanField(default=False, verbose_name="Processado"),
                ),
                (
                    "processing_errors",
                    models.TextField(
                        blank=True, null=True, verbose_name="Erros de Processamento"
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Recebido em"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Processado em"
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Webhook TheMembers",
                "verbose_name_plural": "Logs de Webhook TheMembers",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="TheMembersIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("active", "Ativa"),
                            ("failed", "Falhou"),
                            ("disabled", "Desabilitada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "integration_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Integração"
                    ),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última Sincronização"
                    ),
                ),
                (
                    "sync_errors",
                    models.TextField(
                        blank=True, null=True, verbose_name="Erros de Sincronização"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.course",
                        verbose_name="Curso",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="themembers.themembersproduct",
                        verbose_name="Produto TheMembers",
                    ),
                ),
            ],
            options={
                "verbose_name": "Integração TheMembers",
                "verbose_name_plural": "Integrações TheMembers",
                "ordering": ["-integration_date"],
                "unique_together": {("course", "product")},
            },
        ),
    ]
