# Generated by Django 4.2.21 on 2025-08-31 02:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0013_course_course_video_course_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text='Nome do cliente', max_length=200, verbose_name='Nome do Cliente')),
                ('user_email', models.EmailField(help_text='Email do cliente', max_length=254, verbose_name='Email do Cliente')),
                ('rating', models.IntegerField(help_text='Avaliação de 1 a 5 estrelas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação')),
                ('title', models.CharField(help_text='Título da avaliação', max_length=200, verbose_name='Título da Avaliação')),
                ('comment', models.TextField(help_text='Comentário detalhado', verbose_name='Comentário')),
                ('is_approved', models.BooleanField(default=False, help_text='Avaliação aprovada para exibição', verbose_name='Aprovado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Avaliação de Curso',
                'verbose_name_plural': 'Avaliações de Cursos',
                'ordering': ['-created_at'],
            },
        ),
    ]
