# Generated by Django 4.2.21 on 2025-08-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CoursePerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_title",
                    models.CharField(max_length=200, verbose_name="Título do Curso"),
                ),
                (
                    "total_sales",
                    models.IntegerField(default=0, verbose_name="Total de Vendas"),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Receita Total",
                    ),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Taxa de Conversão (%)",
                    ),
                ),
                (
                    "last_sale_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Última Venda"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Performance do Curso",
                "verbose_name_plural": "Performance dos Cursos",
                "ordering": ["-total_revenue"],
            },
        ),
        migrations.CreateModel(
            name="StudentActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email do Aluno"),
                ),
                (
                    "student_name",
                    models.CharField(max_length=200, verbose_name="Nome do Aluno"),
                ),
                (
                    "course_title",
                    models.CharField(max_length=200, verbose_name="Título do Curso"),
                ),
                ("last_access", models.DateTimeField(verbose_name="Último Acesso")),
                (
                    "access_count",
                    models.IntegerField(default=1, verbose_name="Contador de Acessos"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Atividade do Aluno",
                "verbose_name_plural": "Atividades dos Alunos",
                "ordering": ["-last_access"],
            },
        ),
        migrations.CreateModel(
            name="DashboardMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("sales", "Vendas"),
                            ("revenue", "Receita"),
                            ("students", "Alunos"),
                            ("courses", "Cursos"),
                            ("conversion", "Taxa de Conversão"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Métrica",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Valor"
                    ),
                ),
                ("date", models.DateField(verbose_name="Data")),
                (
                    "period",
                    models.CharField(
                        default="daily", max_length=20, verbose_name="Período"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Métrica do Dashboard",
                "verbose_name_plural": "Métricas do Dashboard",
                "ordering": ["-date", "-created_at"],
                "unique_together": {("metric_type", "date", "period")},
            },
        ),
    ]
