# Generated by Django 4.2.21 on 2025-08-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_category_course_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="themembers_product_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="ID Produto TheMembers",
            ),
        ),
    ]
