# Generated by Django 4.2.21 on 2025-08-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_course_themembers_product_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="image_preview",
        ),
        migrations.RemoveField(
            model_name="course",
            name="video_url",
        ),
        migrations.AddField(
            model_name="course",
            name="course_image",
            field=models.URLField(
                blank=True, null=True, verbose_name="URL da Imagem do Curso"
            ),
        ),
    ]
