# Generated by Django 4.2.21 on 2025-08-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0009_replace_video_with_course_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="courses/images/",
                verbose_name="Imagem do Curso",
            ),
        ),
    ]
