# Generated by Django 4.2.21 on 2025-08-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("professors", "0001_initial"),
        ("courses", "0010_change_course_image_to_file_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="courses",
                to="courses.category",
                verbose_name="Categorias",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="professors",
            field=models.ManyToManyField(
                blank=True,
                related_name="courses",
                to="professors.professor",
                verbose_name="Professores",
            ),
        ),
    ]
