# Generated by Django 4.2.21 on 2025-08-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0011_course_categories_course_professors"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="whatsapp_group_link",
            field=models.URLField(
                blank=True,
                help_text="Link para o grupo do WhatsApp do curso",
                null=True,
                verbose_name="Link do Grupo WhatsApp",
            ),
        ),
    ]
