# Generated by Django 4.2.21 on 2025-08-31 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_whatsapp_group_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_video',
            field=models.FileField(blank=True, help_text='Vídeo para mostrar nos detalhes do curso', null=True, upload_to='courses/videos/', verbose_name='Vídeo do Curso'),
        ),
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL do YouTube, Vimeo ou outro serviço', null=True, verbose_name='URL do Vídeo'),
        ),
    ]
