# Generated by Django 4.2.21 on 2025-09-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_course_video_course_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allow_bank_slip',
            field=models.BooleanField(default=True, verbose_name='Habilitar Boleto'),
        ),
        migrations.AddField(
            model_name='course',
            name='allow_boleto_installments',
            field=models.BooleanField(default=False, verbose_name='Habilitar Boleto Parcelado'),
        ),
        migrations.AddField(
            model_name='course',
            name='allow_credit_card',
            field=models.BooleanField(default=True, verbose_name='Habilitar Cartão de Crédito'),
        ),
        migrations.AddField(
            model_name='course',
            name='allow_pix',
            field=models.BooleanField(default=True, verbose_name='Habilitar PIX'),
        ),
        migrations.AddField(
            model_name='course',
            name='max_boleto_installments',
            field=models.IntegerField(default=12, verbose_name='Parcelas máx. no boleto'),
        ),
    ]
