# Generated by Django 4.2.21 on 2025-09-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_course_allow_bank_slip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='BookOpen', max_length=50, verbose_name='Ícone'),
        ),
    ]
