# Generated by Django 4.2.21 on 2025-08-24 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sales", "0003_sale_address_sale_address_complement_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsaasWebhookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "webhook_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ID do Webhook"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(max_length=100, verbose_name="Tipo do Evento"),
                ),
                (
                    "payment_id",
                    models.CharField(max_length=100, verbose_name="ID do Pagamento"),
                ),
                ("raw_data", models.JSONField(verbose_name="Dados Recebidos")),
                (
                    "processed",
                    models.BooleanField(default=False, verbose_name="Processado"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Processado em"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensagem de Erro"),
                ),
                (
                    "received_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Recebido em"),
                ),
            ],
            options={
                "verbose_name": "Log de Webhook Asaas",
                "verbose_name_plural": "Logs de Webhook Asaas",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="AsaasPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asaas_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ID Asaas"
                    ),
                ),
                (
                    "asaas_customer_id",
                    models.CharField(max_length=100, verbose_name="ID Cliente Asaas"),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("BOLETO", "Boleto"),
                            ("CREDIT_CARD", "Cartão de Crédito"),
                            ("PIX", "PIX"),
                            ("TRANSFER", "Transferência"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Pagamento",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("RECEIVED", "Recebido"),
                            ("CONFIRMED", "Confirmado"),
                            ("OVERDUE", "Vencido"),
                            ("REFUNDED", "Reembolsado"),
                        ],
                        default="PENDING",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Data de Vencimento")),
                (
                    "payment_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data do Pagamento"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "customer_name",
                    models.CharField(max_length=200, verbose_name="Nome do Cliente"),
                ),
                (
                    "customer_email",
                    models.EmailField(max_length=254, verbose_name="Email do Cliente"),
                ),
                (
                    "customer_cpf_cnpj",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="CPF/CNPJ"
                    ),
                ),
                (
                    "pix_qr_code",
                    models.TextField(blank=True, verbose_name="QR Code PIX"),
                ),
                (
                    "bank_slip_url",
                    models.URLField(blank=True, verbose_name="URL do Boleto"),
                ),
                (
                    "webhook_received",
                    models.BooleanField(default=False, verbose_name="Webhook Recebido"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "sale",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asaas_payment",
                        to="sales.sale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagamento Asaas",
                "verbose_name_plural": "Pagamentos Asaas",
                "ordering": ["-created_at"],
            },
        ),
    ]
