# Generated by Django 4.2.21 on 2025-08-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration_asas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asaaspayment",
            name="payment_link_url",
            field=models.URLField(blank=True, verbose_name="URL do Link de Pagamento"),
        ),
    ]
