# Generated by Django 4.2.21 on 2025-08-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration_asas", "0002_asaaspayment_payment_link_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="asaaspayment",
            name="invoice_url",
            field=models.URLField(blank=True, verbose_name="URL da Fatura"),
        ),
    ]
