# Generated by Django 4.2.21 on 2025-08-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration_asas", "0003_asaaspayment_invoice_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asaaspayment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("BOLETO", "Boleto"),
                    ("CREDIT_CARD", "Cartão de Crédito"),
                    ("PIX", "PIX"),
                ],
                max_length=20,
                verbose_name="Tipo de Pagamento",
            ),
        ),
    ]
