# Generated by Django 4.2.21 on 2025-09-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_asas', '0004_alter_asaaspayment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='asaaspayment',
            name='installment_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Parcelas'),
        ),
        migrations.AddField(
            model_name='asaaspayment',
            name='installment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID do Parcelamento'),
        ),
        migrations.AddField(
            model_name='asaaspayment',
            name='installment_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor por Parcela'),
        ),
    ]
