# Generated by Django 4.2.21 on 2025-08-31 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_alter_testimonial_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='video',
            field=models.FileField(blank=True, help_text='Vídeo do depoimento', null=True, upload_to='testimonials/videos/', verbose_name='Vídeo do Depoimento'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL do YouTube, Vimeo ou outro serviço', null=True, verbose_name='URL do Vídeo'),
        ),
    ]
