# Generated by Django 4.2.21 on 2025-08-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="themembers_subscription_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="ID Assinatura TheMembers",
            ),
        ),
    ]
