# Generated by Django 4.2.21 on 2025-08-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_sale_themembers_subscription_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Endereço"),
        ),
        migrations.AddField(
            model_name="sale",
            name="address_complement",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Complemento"
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="address_number",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Número"
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Cidade"
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="cpf_cnpj",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="CPF/CNPJ"
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="neighborhood",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Bairro"
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="CEP"
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="state",
            field=models.CharField(
                blank=True, max_length=2, null=True, verbose_name="Estado"
            ),
        ),
    ]
