# Generated by Django 4.2.21 on 2025-08-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0003_sale_address_sale_address_complement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("pix", "PIX"),
                    ("credit_card", "Cartão de Crédito"),
                    ("bank_slip", "Boleto"),
                ],
                max_length=20,
                verbose_name="Método de Pagamento",
            ),
        ),
    ]
