# Generated by Django 4.2.21 on 2025-08-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0004_alter_sale_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="themembers_temp_password",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Senha Temporária TheMembers",
            ),
        ),
    ]
