# Generated by Django 4.2.21 on 2025-08-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0005_sale_themembers_temp_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="themembers_action",
            field=models.CharField(
                choices=[
                    ("new_user", "Usuário Novo"),
                    ("existing_user", "Usuário Existente"),
                    ("recreated_user", "Usuário Recriado"),
                ],
                default="new_user",
                max_length=20,
                verbose_name="Tipo de Ação TheMembers",
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="themembers_subscription_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="ID da Assinatura TheMembers",
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="themembers_temp_password",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Senha Temporária TheMembers",
            ),
        ),
    ]
