# Generated by Django 4.2.21 on 2025-08-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0006_sale_themembers_action_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="themembers_action",
        ),
        migrations.AlterField(
            model_name="sale",
            name="themembers_subscription_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="ID Assinatura TheMembers",
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="themembers_temp_password",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Senha Temporária TheMembers",
            ),
        ),
    ]
