# Generated by Django 4.2.21 on 2025-09-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_remove_sale_themembers_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='bank_slip_installment_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº de parcelas no boleto'),
        ),
        migrations.AddField(
            model_name='sale',
            name='bank_slip_installment_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da parcela (boleto)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('pix', 'PIX'), ('credit_card', 'Cartão de Crédito'), ('bank_slip', 'Boleto'), ('bank_slip_installments', 'Boleto Parcelado')], max_length=30, verbose_name='Método de Pagamento'),
        ),
    ]
